export const LOREM = {
	IPSUM:
		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac semper sapien, et consectetur nisl. Aenean magna erat, ultrices sit amet auctor quis, finibus at odio. Nulla finibus tempor molestie. Etiam maximus non lectus et auctor. In auctor feugiat massa sed tempus. Maecenas euismod nisi id metus ornare lobortis. Proin arcu tortor, ornare in ante vitae, porta convallis sem. Maecenas id nisl hendrerit, suscipit arcu et, feugiat urna. Proin rutrum nulla sed enim interdum, vitae ultrices lacus dapibus. Integer egestas dictum dignissim. Ut congue nisi augue. Quisque gravida ipsum id odio commodo bibendum.',
	PRESENT:
		'Praesent elementum a ante eget sollicitudin. Nunc vestibulum, ex id mollis suscipit, quam ante fermentum massa, in pulvinar libero tortor sed lacus. Ut convallis nisl leo. Proin a sapien eu ante vestibulum venenatis id et leo. Cras at vulputate massa. Suspendisse fringilla dictum metus. Nulla non purus congue, suscipit arcu nec, facilisis risus. Maecenas lectus neque, egestas non rhoncus id, interdum vel dolor. Maecenas sit amet leo consequat nulla consectetur rhoncus.',
	MAECENAS:
		'Maecenas justo nunc, dignissim ut euismod ut, tempus in felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin interdum convallis sapien. Fusce hendrerit rutrum nisl sit amet egestas. Quisque tincidunt eros odio, et accumsan mi suscipit vitae. Sed nec libero ac purus feugiat placerat. Quisque eu sagittis tellus, quis porttitor neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent magna diam, dictum eget molestie id, feugiat vitae justo.',
	SUSPENDISSE:
		'Suspendisse efficitur libero in lorem rhoncus, vel dapibus nunc blandit. Etiam tristique dictum tempus. Morbi eget justo rhoncus, interdum sapien ac, posuere purus. Suspendisse elementum lorem id hendrerit consectetur. Proin auctor mollis lorem, egestas rutrum nulla hendrerit nec. Nunc bibendum consequat nisi. Suspendisse fringilla non velit ac posuere. Integer laoreet ipsum id consequat ultricies. Duis ut augue tellus. Maecenas lacus libero, imperdiet ut pulvinar eu, porttitor quis erat. Curabitur in nisl non lacus accumsan pharetra.',
	NUNC: 'Nunc consequat iaculis lectus, non venenatis mi interdum pretium. Sed lacinia ante vitae enim fermentum feugiat. Praesent vestibulum ligula dui, sed fringilla libero iaculis quis. Proin faucibus ligula at sapien venenatis, lacinia semper arcu laoreet. Etiam ultrices, elit at tristique sodales, dui leo vehicula massa, nec laoreet lorem ligula vitae elit. Cras tristique a sem id pretium. Vivamus in egestas libero. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ultrices interdum tristique.'
};
